services:
  pytest:
    image: gitlab.hamrah.in:5555/zarinpal_v4/qa/quality-gate:latest
    container_name: pytest
    ports:
      - 4444:4444
      - 7900:7900
    shm_size: '2g'
    networks:
      - pytest
    labels:
      logging: "promtail"
      logging_jobname: "containerlogs"
networks:
  pytest:
    name: pytest
    driver: bridge
    # external: true
